name: Deprecations

on:
  push:
    branches:
      - release-please--branches--develop--components--daffodil

jobs:
  build:
    name: Check for Removals
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.19.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: graycoreio/github-actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          use-stamp-cache: true

      - name: Check for Removals
        run: |
          cd tools/release
          npx gulp checkForRemovals